#!/bin/sh

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in
   login*|node*|gwd*)
       echo "Configuration: Cluster (TU Berlin, GWDG, IFI)"
       CC="gcc" \
       PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig" \
       CPPFLAGS="-I $HOME/usr/include" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O2 -L$HOME/usr/lib" \
       ./configure --enable-libarchive --prefix=$HOME/usr
       ;;       
   scarecrow*|sec01*)
       echo "Configuration: Laptop (Goettingen)"
       CC="gcc" \
       LDFLAGS="-L/usr/local/opt/libarchive/lib" \
       CPPFLAGS="-I/usr/local/opt/libarchive/include" \
       CFLAGS="-g -pedantic -pipe -O2" \
       ./configure --enable-libarchive --prefix=/opt/rieck
       ;;
   kindl*)
       echo "Configuration: Kindl (OpenBSD)"
       CC="gcc" \
       LDFLAGS="-L/usr/local/lib" \
       CPPFLAGS="-I/usr/local/include" \
       CFLAGS="-g -pedantic -pipe -O2" \
       ./configure --enable-libarchive --prefix=/opt/rieck
       ;;
   schulle*)
       echo "Configuration: Schulle (ESX Cluster)"
       PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" \
       CC="gcc" \
       CFLAGS="-g -pedantic -pipe -O2" \
       ./configure --enable-libarchive
       ;;
   evaltime)
       echo "Configuration: Run-time evaluation"
       CC="gcc" \
       CFLAGS="-g -pedantic -pipe -O2" \
       ./configure --enable-libarchive --enable-evaltime
       ;;
   *)    
       echo "Unknown system or configuration"
       exit
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

echo
echo "Done. Press <enter> to compile"
read x

# Compile
make clean 
make -j 4 
