#!/bin/sh

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in

   node*)
       echo "Configuration: Node"
       CC="gcc" \
       CPPFLAGS="-I $HOME/usr/include" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native -L$HOME/usr/lib" \
       CXXFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native -L$HOME/usr/lib" \
       ./configure --enable-openmp --enable-libarchive --prefix=$HOME/usr
       ;;       

   twoface*|rieck*)
       echo "Configuration: Twoface/Rieck"
       CC="gcc-mp-4.4" \
       CXX="g++-mp-4.4" \
       CFLAGS="-march=native -DDEBUG -g -pedantic -pipe" \
       CXXFLAGS="-march=native -DDEBUG -g -pedantic -pipe" \
       ./configure --enable-openmp --enable-libarchive --prefix=/opt/rieck
       ;;

   *)    
       echo "Configuration: Standard"
       CFLAGS="-g -pedantic -pipe -DDEBUG" \
       ./configure 
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

echo
echo "Done. Press <enter> to compile"
read

# Compile
make clean 
make -j 4 
