#!/bin/sh

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in

   gwd*)
       echo "Configuration: Cluster (GWDG)"
       CC="gcc" \
       PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig" \
       CPPFLAGS="-I $HOME/local/include" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -L$HOME/local/lib" \
       ./configure --enable-libarchive --prefix=$HOME/local
       ;;       

   node*)
       echo "Configuration: Cluster (TU Berlin)"
       CC="gcc" \
       PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig" \
       CPPFLAGS="-I $HOME/usr/include" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native -L$HOME/usr/lib" \
       ./configure --enable-libarchive --prefix=$HOME/usr
       ;;       

   twoface*|rieck*)
       echo "Configuration: Twoface/Rieck"
       CC="gcc-mp-4.4" \
       CFLAGS="-DDEBUG -g -pedantic -pipe" \
       ./configure --enable-openmp --enable-libarchive --prefix=/opt/rieck
       ;;

   ubuntu)    
       echo "Configuration: Standard"
       CFLAGS="-g -pedantic -pipe -DDEBUG"  \
       ./configure --enable-libarchive --enable-openmp
       ;;

   *)    
       echo "Configuration: Standard"
       CFLAGS="-g -pedantic -pipe -DDEBUG" \
       ./configure 
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

echo
echo "Done. Press <enter> to compile"
read

# Compile
make clean 
make -j 4 
