=pod

=head1 NAME

B<sally> -- a tool for embedding strings in vector spaces

=head1 SYNOPSIS

B<sally> [B<-hvV>] I<config> I<input> I<output>

=head1 DESCRIPTION

B<sally> is a tool for mapping a set of strings to a set of vectors. This
mapping is referred to as embedding.  The conversion from strings to vectors
allows for easily applying techniques from statistics, machine learning and
data mining for analysis of string data.  This is the very intention of
B<sally>.  

B<sally> first loads a set of strings from the I<input> source.  The
embedding is then carried out by characterizing the strings using a set of
features.  Depending on the I<config> file, these features refer to all
words contained in the strings, to all byte sequences of length n (byte
n-grams) or to all word sequences of length n (word n-grams).  By counting
the occurences of the features, B<sally> constructs a vector for each
string.  Each dimension in the vectors corresponds to the occurences of a
particular feature.  The resulting vectors are finally normalized and
written to the I<output> destination.

A detailed introduction to the embedding of strings is provided by Rieck &
Laskov, "Linear-time computation of similarity measures for sequential
data", Journal of Machine Learning Research, 2008.

    .---------.                        .----------.
    |   dir   |                        |  libsvm  |
    |   arc   |   \   .---------.   /  |   list   |
    |  lines  |   --  |  Sally  |  --  |  matlab  |
    |  fasta  |   /   '---------'   \  |  python  |
    '---------'                        '----------'
       Input                              Output 

=head2 Input formats

=over 12

=item B<dir> 

The input strings are available as binary files in a directory. The name of
the directory is given as I<input> to B<sally>.

=item B<arc> 

The input strings are available as binary files in an archive, such as a zip
or tgz archive.  The name of the archive is given as I<input> to B<sally>.

=item B<lines> 

The input strings are available as lines in a text file. The name of the
file is given as I<input> to B<sally>. The lines need to be seperated by
newline and may not contain the NUL character.

=back 

=head2 Output formats

=over 12

=item B<libsvm> 

The feature vectors of the embedded strings are stored in libsvm format. 
The name of the output file is given as I<output> to B<sally>.

=item B<list> 

The feature vectors of the embedded strings are stored as a list of
dimensions, features and respective values.  The name of the output file is
given as I<output> to B<sally>.

=back

=head1 COPYRIGHT

Copyright (c) 2010 Konrad Rieck (konrad@mlsec.org)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.  This program is distributed without
any warranty. See the GNU General Public License for more details.
      
=cut
