=pod

=head1 NAME

B<sally> -- a tool for embedding strings in vector spaces

=head1 SYNOPSIS

B<sally> [B<-hvV>] I<config> I<input> I<output>

=head1 DESCRIPTION

B<sally> is a small tool for mapping a set of strings to a set of
vectors. This mapping is referred to as embedding and allows for
applying techniques from statistics, machine learning and data mining
for analysis of string data. This is the very intention of B<sally>.

The embedding is carried out incrementally, where B<sally> first loads
a chunk of strings from I<input>, computes the mapping to vectors and
then writes the chunk of vectors to I<output>. The configuration of
this process, such as the input format, the embedding type and the
output format, are specified in the file I<config>.

    .---------.                        .----------.
    |   dir   |                        |   text   |
    |   arc   |   \   .---------.   /  |  libsvm  |
    |  lines  |   --  |  Sally  |  --  |  matlab  |
    |   ...   |   /   '---------'   \  |   ...    |
    '---------'                        '----------'
       Input           Embedding          Output 


=head2 Embedding strings

B<sally> implements a standard technique for mapping strings to a
vector space, which is often referred to as I<vector space model> or
I<bag-of-words model>. The strings are characterized by a set of
features, where each feature is associated with one dimension of the
resulting vector space. B<sally> supports the following types of
features:

=over 16

=item B<words>

The strings are partitioned into substrings (words) using a set of
delimiter characters. Such partitioning is typical for natural
language processing, where the delimiters are usually defined as
whitespace and punctation symbols.

=item B<byte n-grams>

The strings are characterized by all possible byte sequences of a
fixed length n (byte n-grams). These features are frequently used if
no information about the structure of strings is available, such as in
bioinformatics or computer security.

=item B<word n-grams>

The strings are characterized by all possible word sequences of a fixed
length n (word n-grams).  These features require the definition of a set of
delimiters and a length n.  They are often used in natural language
processing as a coarse way for capturing structure of text.

=back

A detailed introduction to the embedding of strings is provided by Rieck &
Laskov, "Linear-time computation of similarity measures for sequential
data", Journal of Machine Learning Research, 2008.

=head2 Input formats

=over 16

=item B<dir> 

The input strings are available as binary files in a directory and the name
of the directory is given as I<input> to B<sally>. The suffixes of the
files are used as labels for the extracted vectors.

=item B<arc> 

The input strings are available as binary files in a compressed archive,
such as a zip or tgz archive.  The name of the archive is given as I<input>
to B<sally>.  The suffixes of the files are used as labels for the extracted
vectors.

=item B<lines> 

The input strings are available as lines in a text file. The name of the
file is given as I<input> to B<sally>.  No label information is supported by
this input format.  The lines need to be seperated by newline and may not
contain the NUL character.

=back 

=head2 Output formats

=over 16

=item B<libsvm> 

The feature vectors of the embedded strings are stored in libsvm format. 
The name of the output file is given as I<output> to B<sally>.

=item B<text> 

The feature vectors of the embedded strings are stored as a plain text using
a list of dimensions, features and respective values.  The name of the
output file is given as I<output> to B<sally>.

=item B<matlab>

The feature vectors of the embedded strings are stored in matlab format
(v5).  The vectors are stored as a cell array with 2 x n dimensions, where
the first row holds the source of each vector and the second the vector
itself as a sparse array.  The name of the output file is given as I<output>
to B<sally>.

=back

=head1 COPYRIGHT

Copyright (c) 2010 Konrad Rieck (konrad@mlsec.org)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.  This program is distributed without
any warranty. See the GNU General Public License for more details.
      
=cut
